# Generated by Django 2.1.7 on 2019-03-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='gitUser',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
