# Generated by Django 2.1.7 on 2019-03-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectUser', '0002_projectuser_gituser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='gitUser',
            field=models.CharField(max_length=255, verbose_name='Git User Name'),
        ),
    ]
