# Generated by Django 2.2.3 on 2019-07-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloghome',
            old_name='body',
            new_name='intro',
        ),
    ]
