# Generated by Django 2.2.3 on 2019-07-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0003_auto_20190714_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=255, verbose_name='name_category')),
                ('description', models.CharField(max_length=255, verbose_name='description_category')),
                ('colour', models.CharField(max_length=255, verbose_name='colour_category')),
                ('catergory_image', models.ImageField(blank=True, upload_to='img/blog/blog_category')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
