# Generated by Django 2.2.3 on 2019-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190804_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
