# Generated by Django 2.1.7 on 2019-04-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(max_length=100)),
                ('contact_email', models.EmailField(max_length=70)),
                ('contact_phone_number', models.TextField(blank=True)),
                ('contact_message', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
