# Generated by Django 2.2.3 on 2019-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=70)),
                ('contact_phone_number', models.CharField(blank=True, max_length=70)),
                ('contact_message', models.CharField(max_length=200)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-contact_date',),
            },
        ),
    ]
