# Generated by Django 2.2 on 2019-04-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_contact_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-contact_date',)},
        ),
    ]
