# Generated by Django 2.2.3 on 2019-07-11 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='projectName')),
                ('created', models.DateTimeField(verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(verbose_name='Date Updated')),
                ('description', models.TextField(max_length=1000)),
                ('project_link', models.CharField(max_length=100)),
                ('project_image', models.ImageField(blank=True, upload_to='img/project_img/')),
                ('projectHandlier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectUserHandlier', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='project_tag', to='organizer.Tag')),
            ],
            options={
                'ordering': ('-last_updated',),
            },
        ),
    ]
