# Generated by Django 2.1.7 on 2019-02-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prokject_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
