# Generated by Django 2.1.7 on 2019-02-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_prokject_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prokject_link',
            new_name='project_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
