# Generated by Django 2.1.7 on 2019-02-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190219_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-last_updated',)},
        ),
    ]
