# Generated by Django 2.1.7 on 2019-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
        ('projects', '0008_auto_20190219_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='project_tag', to='organizer.Tag'),
        ),
    ]
