# Generated by Django 2.1.7 on 2019-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
