# Generated by Django 2.1.7 on 2019-02-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190220_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img_link',
            new_name='imglink',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='projectName',
        ),
    ]
