# Generated by Django 2.1.7 on 2019-02-20 14:39

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190220_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='projectName'),
        ),
    ]
