# Generated by Django 2.1.7 on 2019-03-13 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20190313_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectHandlier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectUserHandlier', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
