# Generated by Django 2.1.7 on 2019-03-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190314_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, upload_to='upload/files/'),
        ),
    ]
