# Generated by Django 2.1.7 on 2019-03-31 07:54

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190331_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, upload_to=projects.models.project_directory_path),
        ),
    ]
