# Generated by Django 2.1.7 on 2019-04-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20190331_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='project_tag', to='organizer.Tag'),
        ),
    ]
